namespace ClassicUO.Game.Managers;

internal enum CUSTOM_HOUSE_FLOOR_VISION_STATE
{
	CHGVS_NORMAL,
	CHGVS_TRANSPARENT_CONTENT,
	CHGVS_HIDE_CONTENT,
	CHGVS_TRANSPARENT_FLOOR,
	CHGVS_HIDE_FLOOR,
	CHGVS_TRANSLUCENT_FLOOR,
	CHGVS_HIDE_ALL
}
