using System;

namespace ClassicUO.Game.Managers;

[Flags]
internal enum CUSTOM_HOUSE_MULTI_OBJECT_FLAGS
{
	CHMOF_GENERIC_INTERNAL = 1,
	CHMOF_FLOOR = 2,
	CHMOF_STAIR = 4,
	CHMOF_ROOF = 8,
	CHMOF_FIXTURE = 0x10,
	CHMOF_TRANSPARENT = 0x20,
	CHMOF_IGNORE_IN_RENDER = 0x40,
	CHMOF_VALIDATED_PLACE = 0x80,
	CHMOF_INCORRECT_PLACE = 0x100,
	CHMOF_DONT_REMOVE = 0x200,
	CHMOF_PREVIEW = 0x400
}
